[user]
email = "ovedy@oftedal.com"
name = "Ove Oftedal"

[ui]
paginate = "auto"
editor = "nvim"
default-command = ["log", "-n", "20", "--no-pager"]

[aliases]

# diff-editor = "diffconflicts"
#
# [merge-tools.diffconflicts]
# program = "nvim"
# merge-args = [
#     "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
#     "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
# ]
# merge-tool-edits-conflict-markers = true
